@startuml
frontend -> frontend : проверяет, скоро ли протухнет access токен
frontend -> auth_api : /refresh
note left
делает запрос на апи авторизации
передает туда access и refresh токен
c просьбой обновить access токен
endnote
auth_api -> auth_api
note left
берет guid который был зашит в access_token
при генерации токена, и ищет в базе refresh
токен c этим guid.
если есть, то он сверает поступивший refresh_token 
с тем который хранится в базе. Если они равны, значит
refresh токен актуальный. Помимо этого еще проверяется
поле expiresAt на случай если рефреш токен уже протух.
Генерятся новые access и рефреш токены. Новый рефреш токен
записывается в базу с guid, тем самым старый рефреш токен перезаписывается 
на новый. И условие задачи не допускать повтороного использования рефреш токена 
выполняется.
endnote
auth_api -> frontend
note left
возвращает новые access и refresh токен
endnote
@enduml